sudo: false
language: perl
perl:
  - "5.10"
  - "5.14"
  - "5.20"
  - "5.22"
  - "5.24"
  - "blead"
sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
